name: dart_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

dependencies:
  bloc: ^8.1.4
  sqflite_common_ffi: ^2.3.4+4
  sqlite3: ^2.4.7
  uuid: ^4.5.1
  http: ^1.2.2
  logging: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  raylib: ^0.3.0
  ffi: ^1.2.1
  protobuf: ^4.2.0
  logger: ^2.6.1
